# Generated by Django 5.2 on 2025-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
