# Generated by Django 5.2 on 2025-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_advertisement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
