# Generated by Django 5.2 on 2025-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_advertisement_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(),
        ),
    ]
